### ISSUE TITLE
Url has no target

### ISSUE THREAD

**Issue by confile** [lmivan/grails-url-shortener#4]
The urn of the shortenercontroller has no target https://github.com/lmivan/grails-url-shortener/blob/master/grails-app/controllers/net/kaleidos/shortener/ShorternerController.groovy

**Comment by lmivan** [comment]
I'm sorry but I don't really understand your question. What is missing in this file?

https://github.com/lmivan/grails-url-shortener/blob/master/grails-app/controllers/net/kaleidos/shortener/ShortenerController.groovy

**Comment by confile** [comment]
The link above is from your readme page and points to nowhere.

**Comment by lmivan** [comment]
Oh, I see. I've fixed the link.

Thank you very much :-)
