### ISSUE TITLE
 Table 'buddyis.shorten_url' doesn't exist

### ISSUE THREAD

**Issue by confile** [lmivan/grails-url-shortener#5]
After installing the plugin iI get: 

```
 Table 'buddyis.shorten_url' doesn't exist
```

Do I have to do anything to create the database tables?

**Comment by lmivan** [comment]
Hi. 

Yes, you need to create the database tables. Depending on how do you have configured your datasource (update, "empty",...) or if you're using something like database migrations plugin you have different options to create the table.

Another option is to execute `grails schema-export` and execute only the table and indexes creation.

**Comment by confile** [comment]
How do I create the tables?

**Comment by lmivan** [comment]
If you execute `grails schema-export` it will create the file `target/ddl.sql` with the complete database schema creation. Then you just edit the file and execute the sql related with the `shorten_url` table inside your database management tool (I don't know what database you are using)

**Comment by confile** [comment]
I think the plugin should create the tables automatically.

**Comment by lmivan** [comment]
Yes but the plugin can't create the tables if, for example, your `dbCreate` property in `DataSource.groovy` file is not configured with "update". I think if you have the property configured with update the tables will be created at startup.

**Comment by confile** [comment]
I do not use dbCreate = "update" because I use database migration. The async mail plugin is able to create the needed tables without using the update.

**Comment by confile** [comment]
Okay I gues I have to install the plugin and do a migration afterwards.
